### ISSUE TITLE
Syntax error linked to implicit argument passed to HTTPParty.post (line 48)

### ISSUE THREAD

**Issue by MathieuLamiot** [fiedl/github-project-to-csv#2]
**Context**

I just cloned the repository and tried following the steps described in the README file to get my project's data in a CSV.
I did not have ruby on my computer, so I started with a fresh install with Homebrew, and added the needed gems (HTTPParty and pry). Note that I am not experienced in Ruby!

**Observed behavior**

When running the following command:
<code> sudo ./github-project-to-csv/github-project-to-csv.rb --project=https://github.com/users/AgentAGadge/projects/2 --output project2.csv --token xxx  </code>

I get: <code>./github-project-to-csv/github-project-to-csv.rb:48: syntax error, unexpected ','</code>

**Workaround**
I modified github-project-to-csv.rb:48 from:
<code>    @result = HTTParty.post(url, body:, headers:)</code>
to 
<code>    @result = HTTParty.post(url, body: body, headers: headers)</code>

And I got the script running perfectly well!

**Issue**
Am I missing something? Thanks!

**Comment by fiedl** [comment]
Thanks for reporting this issue.

The feature of [omitting keyword arguments with the same name](https://rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted) has been introduced in ruby 3.1.

For the moment, I would ask you to install ruby 3.1 or ruby 3.2 with homebrew. If this version is already installed, it might be that the system does not use the homebrew version but instead the older ruby version preinstalled in macOS.

To fix this issue permanently, I will

- [x] provide a `.ruby-version` file to define the required ruby version ➝ https://github.com/fiedl/github-project-to-csv/commit/ee5f083ce69584f80938d119dc7ef5d92e9b9231
- [x] provide a `docker-compose.yml` file to run the script via docker without installing ruby locally ➝ https://github.com/fiedl/github-project-to-csv/commit/bbdc97e7c2b305e9a92ce597bd7c2cfacb779a0b

**Comment by prad8** [comment]
I had encountered the same error. So I installed ruby 3.2.2.
Now I get this error:
```
ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty
	from <internal:/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

**Comment by fiedl** [comment]
@survivalofthew Thanks for catching this!

Please try running

    gem install pry httparty

or run the script via docker, which installs the required gems automatically:

    docker compose run app bundle exec ruby github-project-to-csv.rb --project https://github.com/users/fiedl/projects/2 --output project.csv --token xxx
