### ISSUE TITLE
Would it be possible to export the descriptions also?

### ISSUE THREAD

**Issue by rraadd88** [fiedl/github-project-to-csv#4]
Hi, this tool is indeed very useful in exporting the basic fields of the tasks from the github projects. Thank you for developing it.
My question is: would it be possible to extend the functionality of the tool to export the descriptions of the tasks as well?
The exported descriptions could be in a string format, minus the images.

**Comment by fiedl** [comment]
Hi, please make an update and try it again. The description should now be available in the `body` column.
