### ISSUE TITLE
Missing date values in csvs

### ISSUE THREAD

**Issue by sakatani** [fiedl/github-project-to-csv#5]
The ruby code misses date values when it exports project data to a CSV file. It seems like this code needs a line to dig date values around [L322](https://github.com/fiedl/github-project-to-csv/blob/90f25af8938cd5d920b803f3acf35cc69e0d53a0/github-project-to-csv.rb#L322) in `field_value_attributes`.

E.g.:
`        field_value_data.dig("date") || \`

**Comment by fiedl** [comment]
I'm adding a test date to https://github.com/users/fiedl/projects/2/views/1 to try this out.

<img width="1549" alt="Bildschirm­foto 2023-07-13 um 21 55 34" src="https://github.com/fiedl/github-project-to-csv/assets/1679688/d726d591-27e0-4d2e-b41c-490d2255a26a">

```
[2023-07-13 21:56:05] fiedl@fiedl-mbp ~/rails/github-project-to-csv main 90f25af
▶ ./github-project-to-csv.rb --project https://github.com/users/fiedl/projects/2 --output project.csv
▶ open project.csv
```

<img width="1125" alt="Bildschirm­foto 2023-07-13 um 21 57 15" src="https://github.com/fiedl/github-project-to-csv/assets/1679688/a9144eb9-02ed-4b78-8d58-d5a245f8babe">

The test date is not exported as reported.

**Comment by fiedl** [comment]
```
[2023-07-13 22:06:04] fiedl@fiedl-mbp ~/rails/github-project-to-csv main e890233
▶ ./github-project-to-csv.rb --project https://github.com/users/fiedl/projects/2 --output project.csv
```

<img width="1045" alt="Bildschirm­foto 2023-07-13 um 22 06 59" src="https://github.com/fiedl/github-project-to-csv/assets/1679688/976a3884-7c23-4f3b-9748-602747bf291a">

**Comment by fiedl** [comment]
@sakatani Thanks for reporting this. Could you update to the latest commit and try it again?

**Comment by sakatani** [comment]
@fiedl This works now. Thank you!
